// Auto-generated by openapi-typescript
// Run: npm run generate:api
// This file provides TypeScript types for the backend API.

export interface components {
  schemas: {
    // Minimal placeholders — generate to update
    TemplateResponse: any;
    ProposalContent: any;
  };
}

